[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/healthcheck"
healthcheckTimeout = 100
restartPolicyType = "on-failure"
numReplicas = 1

[service]
internal_port = 1337 